### ISSUE TITLE
Adding more magnetic connector

### ISSUE THREAD

**Issue by YapZanan** [ChrisChrisLoLo/beyblock20#5]
Is it possible to add more magnetic connector in north and south of the pcb? So every module can be arrange from every other side.

**Comment by YapZanan** [comment]
After looking the gerber file that you provided, I think that might be possible, but I have to resize the north and south size to be bigger. I think I will edit the resistor to THT instead of SMD for easier building.

**Comment by ChrisChrisLoLo** [comment]
Thanks for your interest!

I don't know if adding a north and south connector is currently within scope of this project. I think the biggest design challenges would include what you've mentioned: a larger footprint, new challenges to fit said PCB in a case, specifying an interface for vertical connection, and the fact that we'd have to double up on magnetic connectors, which isn't super cheap at the moment.

For the current scope of the project, I alos want to try to avoid grids  (i.e. there's i2c bus loops introduced), since currently I have no idea what implications that has for the I2C bus. Maybe down the line, with another modular keyboard, this could be explored.

An alternative idea might be to make a taller module if you want an L shaped configuration. Something that would be cool that wouldn't require any changes to the beyblock interface would be to make a tall module where you could either put the beyblock not only on each side, but choose if you want to put it on the upper part of the  side, or put it on the lower part of the side side. Beyblock20 now works with KMK, so if you'd like to play around with it a bit, it's something you could certainly try, as well as any other module idea's you have.

With the THT vs SMD discussion, you're free to make your own THT variant, though I think the reason why I stuck with SMD is that it should hopefully make the board look cleaner, and to hopefully avoid any clearance issues. I'm hoping that the package size I picked is as easy as to solder as the diodes.

**Comment by xor256** [comment]
no, normal strong neodyme magnets, no small conectors
